- name: list of packages in local system
  hosts: local
  connection: local
  become: yes
  tasks:

  - name: list of packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

    # debug:
    #   msg: "This is {{item}}"
    loop:
    - nginx
    - mysql
    - postfix
