- name: # conditions with when: , with < and > symbols
  hosts: local
  connection: local
  vars_prompt: # enter number from command prompt
  - name: number
    prompt: "Enter Any number"
    private: no

  - name: Is it number is greater than or less than
    ansible.builtin.debug:
      msg: "The given number is {{ number }} greater then 0 "
    when: number | int >= 10

  - name: Is it number is greater than or less than
    ansible.builtin.debug:
      msg: "The given number is {{ number }} less then 0 "
    when: number | int <=

  
  