- name: install multiple packages
  hosts: local
  connection: local
  become: yes
  tasks:

  - name: Install Multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present

    loop:
     - nginx
     - mysql
     - git

  - name: Start & Enable Services
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - nginx
      - mysql
      - git
